stages:
  - build
  - run

variables:
 GIT_DEPTH: 0
 # Also needs: privileged: true, volumes = ["/certs/client", "/cache"] in /etc/gitlab-runner/config.toml
 DOCKER_TLS_CERTDIR: "/certs"
 GIT_SUBMODULE_STRATEGY: normal
 # Fixes: Ansible is being run in a world writable directory, see:
 # https://github.com/stackhpc/kayobe-automation/issues/2
 FF_DISABLE_UMASK_FOR_DOCKER_EXECUTOR: "true"

build-image:
  image: docker:stable
  rules:
    - when: always
  services:
    - name: docker:dind
      command: ["--mtu=1450"]
  stage: build
  script:
    - cd .automation/docker/kayobe
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker pull $CI_REGISTRY_IMAGE:latest || true
    - docker build --cache-from $CI_REGISTRY_IMAGE:latest --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA --tag $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest

overcloud service deploy:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  stage: run
  rules:
    - when: manual
  script:
    - .automation/cd/overcloud-service-deploy.sh

overcloud host configure:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  stage: run
  rules:
    - when: manual
  script:
    - .automation/cd/overcloud-host-configure.sh

overcloud deployment image build:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  stage: run
  rules:
    - when: manual
  script:
    - .automation/cd/overcloud-deployment-image-build.sh

kolla diff:
  image: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
  stage: run
  rules:
    - if: $CI_MERGE_REQUEST_ID
  script:
    - .automation/ci/config-diff.sh origin/$CI_MERGE_REQUEST_TARGET_BRANCH_NAME
    - cp /tmp/kayobe-config-diff ${CI_PROJECT_DIR}/kayobe-config-diff.txt
  artifacts:
    expose_as: 'kayobe config diff'
    paths: ['./kayobe-config-diff.txt']
